[package]
name = "rpi_led_matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
artnet_protocol = "0.4.1"
glam = "0.22.0"
palette = "0.6.1"
pv_recorder = "1.1.0"
